[default]
description = "Default permissions for native auth plugin"
permissions = [
  "allow-sign-in-apple",
  "allow-open-oauth-browser",
  "allow-register-push",
  "allow-haptic-feedback",
  "allow-copy-to-clipboard",
  "allow-share",
]
