// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 ellul.ai. All rights reserved.

/**
 * `ellul-spawn-scope` — validating wrapper around `systemd-run --scope`.
 *
 * Deployed to `/usr/local/bin/ellul-spawn-scope` (mode 0755, root-owned).
 * Sole sudoers entry: `$SVC_USER ALL=(root) NOPASSWD: /usr/local/bin/ellul-spawn-scope`.
 *
 * Why this exists
 * ───────────────
 * agent-bridge needs to place pool processes (opencode-serve, cursor-agent acp,
 * codex daemon, Lite-Claude one-shots) and Pro Claude slot processes into
 * specific cgroups (per-sandbox transient slices under
 * `ellul-user-workload.slice`, or directly under it for Pro slots). The way to
 * do that is `systemd-run --scope --slice=<x>.slice --unit=<y> --property=...`,
 * which requires root.
 *
 * Sudoers wildcard matching is brittle. Instead this wrapper takes a fixed
 * argument shape, validates each piece against an explicit allowlist regex,
 * and execs systemd-run only when validation passes.
 *
 * Argument shape
 * ──────────────
 *   ellul-spawn-scope <slice> <unit> <props> -- <cmd> <args...>
 *
 * Where:
 *   <slice>   matches one of:
 *               - ellul-user-workload-sbx-<7-char-id>.slice
 *               - ellul-user-workload.slice
 *   <unit>    matches one of:
 *               - ellul-pool-sbx-<7-char-id>-<adapter>-<scopeId>
 *               - ellul-pro-claude-slot<1-9>
 *               - ellul-probe-<adapter>-<scopeId>
 *   <props>   comma-separated list; each item is from the allowlist:
 *               MemoryHigh=<n>{K,M,G,%}, MemoryMax=<n>{K,M,G,%},
 *               MemorySwapMax=<n>{K,M,G,%}, TasksMax=<n>, CPUQuota=<n>%
 *
 * Probe units (ellul-probe-...) are short-lived host-level inventory queries
 * that must not inherit the bridge's cgroup. They run in
 * ellul-user-workload.slice (no per-sandbox slice — probes are host-mode by
 * definition; no project namespace to enter). Same security envelope as the
 * existing host-bypass path: same binary, same egress allowlist, same
 * AppArmor profile; cgroup membership is the only delta.
 *
 * Spec: docs/v2/architecture/resource-v2/03-spawn-routing.md
 */

const SCRIPT = `#!/bin/bash
# ellul-spawn-scope — validating wrapper around systemd-run --scope
# DO NOT EDIT — generated by packages/vps/src/scripts/workflow/spawn-scope.ts
set -euo pipefail

if [ "$#" -lt 5 ]; then
  echo "usage: ellul-spawn-scope <slice> <unit> <props> -- <cmd> [args...]" >&2
  exit 64
fi

SLICE="$1"; shift
UNIT="$1"; shift
PROPS="$1"; shift
SEP="$1"; shift
if [ "$SEP" != "--" ]; then
  echo "ellul-spawn-scope: expected '--' separator, got '$SEP'" >&2
  exit 64
fi

# ── Validate slice name ────────────────────────────────────────────────
case "$SLICE" in
  ellul-user-workload.slice) ;;
  *)
    if ! [[ "$SLICE" =~ ^ellul-user-workload-sbx-[a-z0-9]{7}\\.slice$ ]]; then
      echo "ellul-spawn-scope: invalid slice '$SLICE' (must match ellul-user-workload.slice OR ellul-user-workload-sbx-<7-char>.slice)" >&2
      exit 65
    fi
    ;;
esac

# ── Validate unit name ─────────────────────────────────────────────────
if ! [[ "$UNIT" =~ ^(ellul-pool-sbx-[a-z0-9]{7}-(claude|opencode|cursor|codex)-[a-zA-Z0-9_-]{1,32}|ellul-pro-claude-slot[1-9]|ellul-probe-(claude|opencode|cursor|codex)-[a-zA-Z0-9_-]{1,32}|ellul-install-[a-zA-Z0-9_-]{1,64})$ ]]; then
  echo "ellul-spawn-scope: invalid unit '$UNIT' (must match ellul-pool-sbx-<id>-<adapter>-<scope>, ellul-pro-claude-slot<N>, ellul-probe-<adapter>-<scope>, OR ellul-install-<name>)" >&2
  exit 65
fi

# ── Validate properties (comma-separated allowlist) ────────────────────
PROP_ARGS=()
if [ -n "$PROPS" ]; then
  IFS=',' read -ra PROP_LIST <<< "$PROPS"
  for prop in "\${PROP_LIST[@]}"; do
    [ -z "$prop" ] && continue
    if ! [[ "$prop" =~ ^(MemoryHigh|MemoryMax|MemorySwapMax|TasksMax|CPUQuota)=[0-9]+(K|M|G|%)?$ ]]; then
      echo "ellul-spawn-scope: invalid property '$prop' (allowed: MemoryHigh|MemoryMax|MemorySwapMax|TasksMax|CPUQuota; values numeric with optional K/M/G/%)" >&2
      exit 65
    fi
    PROP_ARGS+=("--property=$prop")
  done
fi

# ── Probe isolation ────────────────────────────────────────────────────
# Probe units are short-lived inventory queries (~150ms). They don't
# need root — sudo was only needed to call systemd-run. Drop back to
# the calling user so probes find CLI credentials (~/.codex, ~/.claude)
# and don't create root-owned temp files.
SCOPE_UID_ARGS=()
if [[ "$UNIT" =~ ^ellul-probe- ]]; then
  PROBE_TMP="/tmp/ellul-probe-cache"
  mkdir -p "$PROBE_TMP" 2>/dev/null || true
  chmod 1777 "$PROBE_TMP" 2>/dev/null || true
  export TMPDIR="$PROBE_TMP"
  export NODE_OPTIONS="\${NODE_OPTIONS:+\$NODE_OPTIONS }--jitless"

  if [ -n "\${SUDO_USER:-}" ]; then
    SCOPE_UID_ARGS=("--uid=\$SUDO_USER")
    export HOME=\$(eval echo "~\$SUDO_USER")
    export USER="\$SUDO_USER"
    export LOGNAME="\$SUDO_USER"
  fi

  # One-shot: clean pre-isolation V8 .so files from /tmp (runs once per boot)
  LEGACY_GUARD="/tmp/.ellul-probe-legacy-cleaned"
  if [ ! -f "$LEGACY_GUARD" ]; then
    find /tmp -maxdepth 1 -name '.*.so' -user root -mmin +5 -delete 2>/dev/null || true
    touch "$LEGACY_GUARD" 2>/dev/null || true
  fi
fi

# ── Exec systemd-run ───────────────────────────────────────────────────
exec /bin/systemd-run \\
  --quiet --collect --scope \\
  --slice="$SLICE" \\
  --unit="$UNIT" \\
  \${PROP_ARGS[@]+"\${PROP_ARGS[@]}"} \\
  \${SCOPE_UID_ARGS[@]+"\${SCOPE_UID_ARGS[@]}"} \\
  -- "$@"
`;

export function getSpawnScopeScript(): string {
  return SCRIPT;
}

/** Sudoers entry for the wrapper. Single line; visudo-validated by callers. */
export function getSpawnScopeSudoers(svcUser: string): string {
  return `# resource-v2: agent-bridge invokes ellul-spawn-scope to place pool processes
# and Pro Claude slot scopes into per-sandbox transient slices under
# ellul-user-workload.slice. The wrapper validates slice/unit/property names
# against explicit allowlists in-script — sudoers does not need arg patterns.
# Spec: docs/v2/architecture/resource-v2/03-spawn-routing.md
${svcUser} ALL=(root) NOPASSWD: /usr/local/bin/ellul-spawn-scope
`;
}
