// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 ellul.ai. All rights reserved.

/**
 * Scoped sudoers grant for preview unit control.
 *
 * Deployed to `/etc/sudoers.d/ellul-preview-units` (mode 0440, root:root,
 * visudo-validated at install). Grants the service user NOPASSWD access to
 * exactly one binary — `/usr/local/bin/ellul-preview-ctl` — which itself
 * validates action + instance before calling systemctl.
 *
 * No other sudo capability flows through this file. The wrapper and its
 * own immutability (chattr +i) are what actually bound what the agent can
 * do; this grant just lets file-api call the wrapper without a password.
 */

export function getPreviewUnitsSudoers(svcUser: string = 'dev'): string {
  return `# ellul preview unit control — generated by rebuild-all manifest.
# file-api (running as ${svcUser}) calls ellul-preview-ctl to start/stop
# the per-preview systemd template units. The wrapper validates the
# action whitelist and the instance regex before invoking systemctl.
${svcUser} ALL=(root) NOPASSWD: /usr/local/bin/ellul-preview-ctl
`;
}
