// SPDX-License-Identifier: MIT
// Copyright (c) 2025 ellul.ai. All rights reserved.

import { Schema } from "effect";
import {
  ApprovalRequestId,
  EventId,
  IsoDateTime,
  RuntimeItemId,
  RuntimeRequestId,
  ThreadId,
  TurnId,
} from "../ids";
import { ProviderKind } from "./kind";
import {
  AccountRateLimitsUpdatedPayload,
  AccountUpdatedPayload,
  AuthStatusPayload,
  ConfigWarningPayload,
  ContentDeltaPayload,
  DeprecationNoticePayload,
  FilesPersistedPayload,
  HookCompletedPayload,
  HookProgressPayload,
  HookStartedPayload,
  ItemLifecyclePayload,
  McpOauthCompletedPayload,
  McpStatusUpdatedPayload,
  ModelReroutedPayload,
  ProviderRefs,
  RequestOpenedPayload,
  RequestResolvedPayload,
  RuntimeErrorPayload,
  RuntimeEventRaw,
  RuntimeWarningPayload,
  SessionConfiguredPayload,
  SessionExitedPayload,
  SessionStartedPayload,
  SessionStateChangedPayload,
  TaskCompletedPayload,
  TaskProgressPayload,
  TaskStartedPayload,
  ThreadMetadataUpdatedPayload,
  ThreadRealtimeAudioDeltaPayload,
  ThreadRealtimeClosedPayload,
  ThreadRealtimeErrorPayload,
  ThreadRealtimeItemAddedPayload,
  ThreadRealtimeStartedPayload,
  ThreadStartedPayload,
  ThreadStateChangedPayload,
  ThreadTokenUsageUpdatedPayload,
  ToolProgressPayload,
  ToolSummaryPayload,
  TurnAbortedPayload,
  TurnCompletedPayload,
  TurnDiffUpdatedPayload,
  TurnPlanUpdatedPayload,
  TurnProposedCompletedPayload,
  TurnProposedDeltaPayload,
  TurnStartedPayload,
  UserInputRequestedPayload,
  UserInputResolvedPayload,
} from "./event-payloads";

export const ProviderRuntimeEventType = Schema.Literals([
  "session.started",
  "session.configured",
  "session.state.changed",
  "session.exited",
  "thread.started",
  "thread.state.changed",
  "thread.metadata.updated",
  "thread.token-usage.updated",
  "thread.realtime.started",
  "thread.realtime.item-added",
  "thread.realtime.audio.delta",
  "thread.realtime.error",
  "thread.realtime.closed",
  "turn.started",
  "turn.completed",
  "turn.aborted",
  "turn.plan.updated",
  "turn.proposed.delta",
  "turn.proposed.completed",
  "turn.diff.updated",
  "item.started",
  "item.updated",
  "item.completed",
  "content.delta",
  "request.opened",
  "request.resolved",
  "user-input.requested",
  "user-input.resolved",
  "task.started",
  "task.progress",
  "task.completed",
  "hook.started",
  "hook.progress",
  "hook.completed",
  "tool.progress",
  "tool.summary",
  "auth.status",
  "account.updated",
  "account.rate-limits.updated",
  "mcp.status.updated",
  "mcp.oauth.completed",
  "model.rerouted",
  "config.warning",
  "deprecation.notice",
  "files.persisted",
  "runtime.warning",
  "runtime.error",
]);
export type ProviderRuntimeEventType = typeof ProviderRuntimeEventType.Type;

const Base = Schema.Struct({
  eventId: EventId,
  provider: ProviderKind,
  threadId: ThreadId,
  createdAt: IsoDateTime,
  turnId: Schema.optional(TurnId),
  itemId: Schema.optional(RuntimeItemId),
  requestId: Schema.optional(RuntimeRequestId),
  providerRefs: Schema.optional(ProviderRefs),
  raw: Schema.optional(RuntimeEventRaw),
});
export type ProviderRuntimeEventBase = typeof Base.Type;

const ev = <const T extends string, P>(type: T, payload: Schema.Schema<P>) =>
  Schema.Struct({ ...Base.fields, type: Schema.Literal(type), payload });

export const ProviderRuntimeEvent = Schema.Union([
  ev("session.started", SessionStartedPayload),
  ev("session.configured", SessionConfiguredPayload),
  ev("session.state.changed", SessionStateChangedPayload),
  ev("session.exited", SessionExitedPayload),
  ev("thread.started", ThreadStartedPayload),
  ev("thread.state.changed", ThreadStateChangedPayload),
  ev("thread.metadata.updated", ThreadMetadataUpdatedPayload),
  ev("thread.token-usage.updated", ThreadTokenUsageUpdatedPayload),
  ev("thread.realtime.started", ThreadRealtimeStartedPayload),
  ev("thread.realtime.item-added", ThreadRealtimeItemAddedPayload),
  ev("thread.realtime.audio.delta", ThreadRealtimeAudioDeltaPayload),
  ev("thread.realtime.error", ThreadRealtimeErrorPayload),
  ev("thread.realtime.closed", ThreadRealtimeClosedPayload),
  ev("turn.started", TurnStartedPayload),
  ev("turn.completed", TurnCompletedPayload),
  ev("turn.aborted", TurnAbortedPayload),
  ev("turn.plan.updated", TurnPlanUpdatedPayload),
  ev("turn.proposed.delta", TurnProposedDeltaPayload),
  ev("turn.proposed.completed", TurnProposedCompletedPayload),
  ev("turn.diff.updated", TurnDiffUpdatedPayload),
  ev("item.started", ItemLifecyclePayload),
  ev("item.updated", ItemLifecyclePayload),
  ev("item.completed", ItemLifecyclePayload),
  ev("content.delta", ContentDeltaPayload),
  ev("request.opened", RequestOpenedPayload),
  ev("request.resolved", RequestResolvedPayload),
  ev("user-input.requested", UserInputRequestedPayload),
  ev("user-input.resolved", UserInputResolvedPayload),
  ev("task.started", TaskStartedPayload),
  ev("task.progress", TaskProgressPayload),
  ev("task.completed", TaskCompletedPayload),
  ev("hook.started", HookStartedPayload),
  ev("hook.progress", HookProgressPayload),
  ev("hook.completed", HookCompletedPayload),
  ev("tool.progress", ToolProgressPayload),
  ev("tool.summary", ToolSummaryPayload),
  ev("auth.status", AuthStatusPayload),
  ev("account.updated", AccountUpdatedPayload),
  ev("account.rate-limits.updated", AccountRateLimitsUpdatedPayload),
  ev("mcp.status.updated", McpStatusUpdatedPayload),
  ev("mcp.oauth.completed", McpOauthCompletedPayload),
  ev("model.rerouted", ModelReroutedPayload),
  ev("config.warning", ConfigWarningPayload),
  ev("deprecation.notice", DeprecationNoticePayload),
  ev("files.persisted", FilesPersistedPayload),
  ev("runtime.warning", RuntimeWarningPayload),
  ev("runtime.error", RuntimeErrorPayload),
]);
export type ProviderRuntimeEvent = typeof ProviderRuntimeEvent.Type;

export { ApprovalRequestId };
