/*
 * test_manifest.c — exercise the path-substitution and option-string
 * helpers from manifest.c / mountinfo.c. These are pure-text routines
 * that can be unit-tested without crypto.
 *
 * The full manifest-load round-trip needs a signed CBOR blob which is
 * generated by apps/api/scripts/sign-manifests.ts; that integration
 * test runs in CI on Linux with libsodium + libtinycbor present.
 *
 * Build:
 *   gcc -o test-manifest test_manifest.c -I. -O0 -g
 *
 * SPDX-License-Identifier: BUSL-1.1
 * Copyright (c) 2026 ellul.ai. All rights reserved.
 */

#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define EXPECT_EQ_INT(actual, expected, msg) \
    do { \
        if ((actual) != (expected)) { \
            fprintf(stderr, "FAIL: %s — got %d, expected %d (%s:%d)\n", \
                    msg, (int)(actual), (int)(expected), __FILE__, __LINE__); \
            exit(1); \
        } else { \
            fprintf(stderr, "PASS: %s\n", msg); \
        } \
    } while (0)

#define EXPECT_STREQ(actual, expected, msg) \
    do { \
        if (strcmp((actual), (expected)) != 0) { \
            fprintf(stderr, "FAIL: %s — got '%s', expected '%s' (%s:%d)\n", \
                    msg, (actual), (expected), __FILE__, __LINE__); \
            exit(1); \
        } else { \
            fprintf(stderr, "PASS: %s\n", msg); \
        } \
    } while (0)

/* Verbatim copy of the substitution logic in manifest.c so this test
 * binary doesn't need the full source tree. Any divergence here is a
 * test bug; CI cross-checks by linking the real manifest.c too (see
 * the provisioning self-test in ellul-namespaced.sh). */
static int nsd_manifest_substitute(const char *tmpl, const char *project,
                                   const char *home, char *dst, size_t dst_cap) {
    if (!tmpl || !project || !home || !dst || dst_cap == 0) return -1;
    size_t pos = 0;
    const char *p = tmpl;
    while (*p) {
        if (*p == ';' || *p == '|' || *p == '&' || *p == '`' ||
            *p == '$' || *p == '\\' || *p == '"' || *p == '\'') return -1;
        if (*p == '{') {
            if (strncmp(p, "{project}", 9) == 0) {
                size_t pl = strlen(project);
                if (pos + pl >= dst_cap) return -1;
                memcpy(dst + pos, project, pl);
                pos += pl;
                p += 9;
                continue;
            }
            if (strncmp(p, "{home}", 6) == 0) {
                size_t hl = strlen(home);
                if (pos + hl >= dst_cap) return -1;
                memcpy(dst + pos, home, hl);
                pos += hl;
                p += 6;
                continue;
            }
            return -1;
        }
        if (pos + 1 >= dst_cap) return -1;
        dst[pos++] = *p++;
    }
    dst[pos] = 0;
    if (strstr(dst, "..")) return -1;
    if (dst[0] != '/') return -1;
    return 0;
}

/* Verbatim copy of mountinfo.c's option matcher. */
static int nsd_mountinfo_opt_has(const char *opts, const char *needle) {
    if (!opts || !needle) return 0;
    size_t nlen = strlen(needle);
    const char *p = opts;
    while (*p) {
        const char *comma = strchr(p, ',');
        size_t span = comma ? (size_t)(comma - p) : strlen(p);
        if (span >= nlen && strncmp(p, needle, nlen) == 0 &&
            (span == nlen || p[nlen] == '=' || p[nlen] == ',')) {
            return 1;
        }
        if (!comma) break;
        p = comma + 1;
    }
    return 0;
}

int main(void) {
    char dst[256];

    /* Plain substitution. */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("{home}/projects/{project}/x", "sbx-abc1234",
                                "/home/dev", dst, sizeof(dst)),
        0, "plain substitution succeeds");
    EXPECT_STREQ(dst, "/home/dev/projects/sbx-abc1234/x", "plain substitution result");

    /* No placeholders — must still succeed and return identity. */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("/etc/ellul/shield-data", "sbx-abc1234",
                                "/home/dev", dst, sizeof(dst)),
        0, "no-placeholder path passes");
    EXPECT_STREQ(dst, "/etc/ellul/shield-data", "no-placeholder identity");

    /* Path traversal — must reject. */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("/etc/../etc/passwd", "sbx-abc1234",
                                "/home/dev", dst, sizeof(dst)),
        -1, "rejects .. traversal");

    /* Substitution can't smuggle .. via project slug. */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("{home}/projects/{project}", "../etc",
                                "/home/dev", dst, sizeof(dst)),
        -1, "rejects .. inserted via {project}");

    /* Shell-meta in template — reject (defense in depth). */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("/etc/$EVIL", "sbx-abc1234",
                                "/home/dev", dst, sizeof(dst)),
        -1, "rejects $ shell metachar");
    EXPECT_EQ_INT(
        nsd_manifest_substitute("/etc/`whoami`", "sbx-abc1234",
                                "/home/dev", dst, sizeof(dst)),
        -1, "rejects backtick");

    /* Unknown placeholder. */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("{evil}/x", "sbx-abc1234", "/home/dev",
                                dst, sizeof(dst)),
        -1, "rejects unknown placeholder");

    /* Buffer overflow — must reject without writing past `dst`. */
    char small[8];
    EXPECT_EQ_INT(
        nsd_manifest_substitute("{home}/abc/def", "sbx-abc1234",
                                "/home/dev", small, sizeof(small)),
        -1, "rejects when result exceeds dst_cap");

    /* Non-absolute output (template missing leading slash). */
    EXPECT_EQ_INT(
        nsd_manifest_substitute("etc/passwd", "sbx-abc1234",
                                "/home/dev", dst, sizeof(dst)),
        -1, "rejects non-absolute output");

    /* Option matcher: positive cases. */
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("rw,nosuid,nodev,relatime", "ro"), 0,
                  "ro not present in rw mount");
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("ro,nosuid", "ro"), 1,
                  "ro at position 0");
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("nosuid,ro", "ro"), 1,
                  "ro at end");
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("size=1M,mode=755", "size"), 1,
                  "size=N matches `size` needle");
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("size=1M", "mode"), 0,
                  "mode not present in size-only");
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("hidepid=2,nosuid", "hidepid=2"), 1,
                  "exact-match opt with value");
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("hidepid=invisible", "hidepid=2"), 0,
                  "hidepid value mismatch rejected");
    /* Substring trap — `nodev` is not a prefix of `nodevicemock`. */
    EXPECT_EQ_INT(nsd_mountinfo_opt_has("nodevicemock", "nodev"), 0,
                  "rejects substring without separator");

    fprintf(stderr, "all manifest tests passed\n");
    return 0;
}
