// AUTO-GENERATED by pop-client-bundle.build.mjs — do not edit.
// Regenerate: pnpm --filter @ellul.ai/vps build

export interface PopClientAsset {
  /** SRI integrity hash (sha384) for <script integrity="..."> and CSP */
  sri: string;
  /** Content-addressable ETag for HTTP caching */
  etag: string;
  /** Bundle size in bytes */
  size: number;
  /** Whether a source map is available */
  hasSourceMap: boolean;
}

export interface PopClientManifest {
  [filename: string]: PopClientAsset;
}

export const POP_CLIENT_MANIFEST: PopClientManifest = {
  "session-pop.js": {
    sri: "sha384-CAWUzsnPMjejU6OzyYkOEGNyBbpYVZBt4pBSFkYg0LruX/qb/6ZSkDql+2ZGUhw3",
    etag: "\"ad5efadccaf863ea\"",
    size: 10474,
    hasSourceMap: true,
  },
  "pop-sw.js": {
    sri: "sha384-YAoBuv2cDUwdVwl2OTo4Omk3ARwNI5XIQfOlA9g7iB5EhkNSKZhdkLl2XuQf8pXg",
    etag: "\"df62de1c041a456e\"",
    size: 2871,
    hasSourceMap: true,
  },
  "terminal-init.js": {
    sri: "sha384-UngLNc4h2mcT3y25zsj9y820/nJk0A0a2DNDWyFEuNQw/c2gVWBkcLdd7tyFvdH5",
    etag: "\"1d00e147d76e1381\"",
    size: 1826,
    hasSourceMap: true,
  },
};
