// SPDX-License-Identifier: MIT
// Copyright (c) 2025 ellul.ai. All rights reserved.
// Auto-aggregated namespace tree for ja. Edit the per-namespace JSON
// files in this directory; do not edit this file by hand unless adding a
// new namespace.

import agents from "./agents.json";
import auth from "./auth.json";
import authors from "./authors.json";
import blog from "./blog.json";
import brand from "./brand.json";
import chat from "./chat.json";
import codeBrowser from "./codeBrowser.json";
import common from "./common.json";
import comparisons from "./comparisons.json";
import consoleNs from "./console.json";
import docs from "./docs.json";
import faq from "./faq.json";
import footer from "./footer.json";
import glossary from "./glossary.json";
import home from "./home.json";
import isolationSpectrum from "./isolationSpectrum.json";
import localeMismatch from "./localeMismatch.json";
import mcp from "./mcp.json";
import nav from "./nav.json";
import og from "./og.json";
import pages from "./pages.json";
import pillars from "./pillars.json";
import pricing from "./pricing.json";
import privacy from "./privacy.json";
import promptEngineering from "./promptEngineering.json";
import signIn from "./signIn.json";
import signUp from "./signUp.json";
import terms from "./terms.json";
import tier from "./tier.json";
import useCases from "./useCases.json";
import vpsShell from "./vpsShell.json";
import webDocs from "./webDocs.json";
import welcome from "./welcome.json";

const messages = {
  ...agents,
  ...auth,
  ...authors,
  ...blog,
  ...brand,
  ...chat,
  ...codeBrowser,
  ...common,
  ...comparisons,
  ...consoleNs,
  ...docs,
  ...faq,
  ...footer,
  ...glossary,
  ...home,
  ...isolationSpectrum,
  ...localeMismatch,
  ...mcp,
  ...nav,
  ...og,
  ...pages,
  ...pillars,
  ...pricing,
  ...privacy,
  ...promptEngineering,
  ...signIn,
  ...signUp,
  ...terms,
  ...tier,
  ...useCases,
  ...vpsShell,
  ...webDocs,
  ...welcome,
};

export default messages;
